print("Tabuada")
ni=(int(input("Digite um número ")))
t1=(f"{ni * 1}")    #redundância (ERRADO!)
t2=(f"{ni * 2}")    #redundância (ERRADO!)
t3=(f"{ni * 3}")    #redundância (ERRADO!)
t4=(f"{ni * 4}")    #redundância (ERRADO!)
t5=(f"{ni * 5}")    #redundância (ERRADO!)
t6=(f"{ni * 6}")    #redundância (ERRADO!)
t7=(f"{ni * 7}")    #redundância (ERRADO!)
t8=(f"{ni * 8}")    #redundância (ERRADO!)
t9=(f"{ni * 9}")    #redundância (ERRADO!)
t10=(f"{ni * 10}")  #redundância (ERRADO!)
print("-"*50)
print(f"{ni}x{1}={t1}")
print(f"{ni}x{2}={t2}")
print(f"{ni}x{3}={t3}")
print(f"{ni}x{4}={t4}")
print(f"{ni}x{5}={t5}")
print(f"{ni}x{6}={t6}")
print(f"{ni}x{7}={t7}")
print(f"{ni}x{8}={t8}")
print(f"{ni}x{9}={t9}")
print(f"{ni}x{10}={t10}")
print("-"*50)

